set(INSTALL_DIR ${OUTPUT_BASE}/install)

set(MODULE_OUTPUT_PATH ${INSTALL_DIR}/lib)
set(LIBRARY_OUTPUT_PATH ${INSTALL_DIR}/lib)
set(ARCHIVE_OUTPUT_PATH ${INSTALL_DIR}/lib)
set(EXECUTABLE_OUTPUT_PATH ${INSTALL_DIR}/bin)

if(WIN32)
  set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG ${EXECUTABLE_OUTPUT_PATH})
  set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE ${EXECUTABLE_OUTPUT_PATH})
  set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG ${LIBRARY_OUTPUT_PATH})
  set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE ${LIBRARY_OUTPUT_PATH})
  set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG ${ARCHIVE_OUTPUT_PATH})
  set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE ${ARCHIVE_OUTPUT_PATH})
endif()


